version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'youtube_converter'
      MYSQL_USER: 'kel'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
  redis:
    image: "redis:5.0.5"

  celery:
    build: .
    command: celery worker -A youtube_converter --loglevel=debug
    env_file:
      - .env
    depends_on:
      - redis
      - db

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/youtube_converter
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
