version: '3'

services:
  redis:
    image: "redis:5.0.5"

  celery:
    build: .
    command: celery worker -A youtube_converter --loglevel=debug
    env_file:
      - .env
    depends_on:
      - redis

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis