# Generated by Django 2.2.1 on 2019-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(verbose_name='download_url')),
            ],
        ),
    ]
