# Generated by Django 2.2.1 on 2019-05-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='load_date',
        ),
        migrations.AlterField(
            model_name='download',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
    ]
