# Generated by Django 2.2.1 on 2019-05-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_auto_20190527_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='url',
            field=models.URLField(),
        ),
    ]
