# Generated by Django 2.2.1 on 2019-06-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_converter', '0004_auto_20190528_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='email',
            field=models.EmailField(default=False, max_length=254, verbose_name='email_to'),
        ),
    ]
