# Generated by Django 2.2.2 on 2019-06-05 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_converter', '0005_download_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='date_load',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
